name: GBA Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm  # Usamos la imagen oficial
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Compile GBA ROM
      run: |
        # Añadimos las rutas de las herramientas manualmente para evitar el error "Command not found"
        export DEVKITPRO=/opt/devkitpro
        export DEVKITARM=/opt/devkitpro/devkitARM
        export PATH=${DEVKITARM}/bin:$PATH
        
        # Ahora sí, compilamos
        cd gba_core
        make

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: mi_juego_gba
        path: gba_core/*.gba
